### ISSUE TITLE
Failed to activate the atom-gist package

### ISSUE THREAD

**Issue by jjwedemyer** [mananshah99/atom-gist#8]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-gist](https://github.com/mananshah99/atom-gist) package, v0.1.1
### Stack Trace

Failed to activate the atom-gist package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/jj_wedemeyer/.atom/packages/atom-gist/lib/atom-gist-view.coffee:1:1)
  at /Users/jj_wedemeyer/.atom/packages/atom-gist/lib/atom-gist-view.coffee:5:3
  at Object.<anonymous> (/Users/jj_wedemeyer/.atom/packages/atom-gist/lib/atom-gist-view.coffee:52:5)
  at Object.<anonymous> (/Users/jj_wedemeyer/.atom/packages/atom-gist/lib/atom-gist-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/jj_wedemeyer/.atom/packages/atom-gist/lib/atom-gist.coffee:1:16)
  at Object.<anonymous> (/Users/jj_wedemeyer/.atom/packages/atom-gist/lib/atom-gist.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -4:44.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:39.5.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:36.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:33.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:33.9.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:31.7.0 core:paste (atom-text-editor.editor.is-focused)
 10x -2:30.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:28.2.0 core:backspace (atom-text-editor.editor.is-focused)
  8x -2:27.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:26.2.0 core:backspace (atom-text-editor.editor.is-focused)
 19x -2:25.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:23.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:21.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:14.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:14.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:01.0 atom-gist:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.7
atom-ctags, v4.1.4
atom-gist, v0.1.1
color-picker, v2.0.7
language-nse, v0.13.0
linter, v1.1.0
linter-chktex, v0.3.2
linter-cpplint, v0.1.4
linter-csslint, v0.0.14
linter-htmlhint, v0.0.17
linter-js-yaml, v1.1.1
linter-jshint, v0.1.7
pigments, v0.8.2

# Dev
No dev packages
```

**Comment by cjwilburn** [comment]
Wanted to second this issue and provide a little more context than the standard auto-issue creation feature in Atom. Looks like a typo on the word `prototype` (being spelled as `protototype` on line 4 of  `~/.atom/packages/atom-gist/lib/atom-gist-view.coffee`
