### ISSUE TITLE
Failed to load the atom-gist package

### ISSUE THREAD

**Issue by vitalii4reva** [mananshah99/atom-gist#9]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [atom-gist](https://github.com/mananshah99/atom-gist) package, v0.1.1
### Stack Trace

Failed to load the atom-gist package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\v.petrenko\.atom\packages\atom-gist\lib\atom-gist-view.coffee:1:1)
    at C:\Users\v.petrenko\.atom\packages\atom-gist\lib\atom-gist-view.coffee:5:3
    at Object.<anonymous> (C:\Users\v.petrenko\.atom\packages\atom-gist\lib\atom-gist-view.coffee:5:3)
    at Object.<anonymous> (C:\Users\v.petrenko\.atom\packages\atom-gist\lib\atom-gist-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\v.petrenko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "language-javascript-semantic",
      "symbols-tree-view",
      "symbols-view"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
atom-commander, v0.5.0
atom-ctags, v4.4.0
atom-gist, v0.1.1
autocomplete-ctags, v0.3.2
ctags-status, v1.3.3
fancy-bracket-matcher, v0.4.1
file-icons, v1.6.11
git-diff-details, v0.21.0
git-log, v0.4.1
highlight-line, v0.11.0
javascript-object-snippets, v0.3.0
javascript-snippets, v1.0.0
language-babel, v0.15.13
language-javascript-jsx, v0.3.7
language-log, v1.1.0
linter, v1.10.0
linter-eslint, v4.0.0
minimap, v4.15.2
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.1
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
nuclide-flow, v0.0.32
pigments, v0.18.1
project-manager, v2.6.5
react, v0.12.10
react-snippets, v0.2.0
redux-snippets, v0.2.1
refactor, v0.6.0
set-syntax, v0.3.0
seti-icons, v0.4.5
source-preview-react, v0.2.0
travis-ci-status, v0.18.0
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by timofonic** [comment]
Any news? Or can this package me marked as deprecated?

**Comment by psphilippe** [comment]
# # @
